### PR TITLE
feat: add ens name and avatar support

### PR DESCRIPTION
**Pull request by bigint**
Screenshot 2021-12-25 at 10 20 26 AM

This works only on mainnet 🙇🏻

### CODE REVIEW

**Comment by dan13ram** [comment]
@akolotov Could you take a look at this? Is this something that we want to merge ?

**Comment by akolotov** [comment]
> @akolotov Could you take a look at this? Is this something that we want to merge ?

Yes, it makes sense to merge it if the changes don't introduce any new issues.

**Comment by bigint** [comment]
@dan13ram Any updates, if this gets merged we will feature the platform in https://ens.domains homepage and tweet about it. Today I'll be pushing some list to the homepage hope omnibridge will be in that list too 🤞🏻 

🙇🏻

**Review by dan13ram — APPROVED** [review]

**Pull request merged**
