### PR TITLE
Fixing bunch of bugs

### LINKED ISSUE #332: Pre-configured JSON rpc endpoint is not overridden by an alternative one
Even if I configure an alternative JSON RPC endpoint, the OB UI still tries to use one specified during the deployment:

image

### LINKED ISSUE #338: "The Gnosis Chain RPC-node is not responding" message appears on the app load
If I try to load https://omni.gnosischain.com/ the following message is displayed:

image

and it disappears in one minute or so. 

The next messages are in the console:

image

Since it is reproducible in 100% (not intermittent), observed by users in different locations and the message disappears shortly it looks like that the issue is on the UI side rather than on the RPC node

### LINKED ISSUE #339: "Error: Please specify amount less than 0" appears
One of our users reported that she got the following message "Error: Please specify amount less than 0". The message does not look very informative and logical since it is not possible to enter negative amount of token.

Could you as part of work on the issue please investigate 
1. Why could such kind of issue appear?
2. Which message could be reported instead to help users with the issue troubleshooting?

### LINKED ISSUE #341: Limits for overridden tokens displayed incorrectly
Here is examples how limits now are displayed for some of overridden tokens:

HNY:
image
OWL:
image
XMOON:
image

### LINKED ISSUE #342: Limits for tokens which are not bridged yet displayed incorrectly
Here is an example for sGNO token originally created on the Gnosis Chain. The token was not bridged yet - there is no such token locked on the OmniBridge contract: https://blockscout.com/xdai/mainnet/address/0xf6A78083ca3e2a662D6dd1703c939c8aCE2e268d/tokens.

image

### LINKED ISSUE #343: Inconsistent view for decimals
Screenshot at Apr 27 11-35-29

### PR DESCRIPTION
**Pull request by dan13ram**
Closes #332 
Closes #338 
Closes #339 
Closes #341 
Closes #342 

Deployed to https://sokol-omnibridge.web.app/

### CODE REVIEW

**Comment by akolotov** [comment]
#343 still exists
image

**Comment by dan13ram** [comment]
@akolotov I've pushed another commit which may have fixed it. Please take a look :)

**Comment by akolotov** [comment]
Can you share more details how #338 was addressed? I still see the following behaviour in some cases:

https://user-images.githubusercontent.com/20793260/165929528-318e4095-35a5-496c-8b48-2a65f512703d.mov

In the screencast it is shown that the message occurs at the moment when the ETH-GC direction is chosen and then disappears automatically.

**Comment by akolotov** [comment]
Could you also check if an new issue with incorrect balance of WETH in GC was introduced by your changes?

image
image

**Comment by dan13ram** [comment]
@akolotov Regarding #338, I have introduced a delay in checking for RPC health for 5 secs after the page load and then every 60 seconds subsequently, but it looks like Gnosis Chain RPC node still fails intermittently. 
Since this issue is happening only for Gnosis Chain I can only gather than the issue is with the RPC node rather our app.

**Comment by akolotov** [comment]
#343 still exists

https://user-images.githubusercontent.com/20793260/166234921-46d4174b-cf34-4936-8a7c-6809ea6da189.mov

**Comment by akolotov** [comment]
Since our users expect fixes for urgent issues I am merging this PR but leave #343 open since it is not addressed yet in full manner.

**Review by akolotov — APPROVED** [review]

**Pull request merged**
