### PR TITLE
feat: Add POA-xDAI bridge

### PR DESCRIPTION
**Pull request by dan13ram**
Deployed to https://sokol-omnibridge.web.app/

### CODE REVIEW

**Comment by akolotov** [comment]
Thanks, I am looking on the staging UI to verify that every thing as expected

**Comment by akolotov** [comment]
I am trying to send Wrapped POA from the xDai chain and UI is stuck on the following step:
image

**Comment by dan13ram** [comment]
@akolotov this was fixed in 61bc7719f8266acdb7bd713c67014ac786b9fc19
Can you try again?

**Comment by akolotov** [comment]
> Can you try again?

Yes, it works.

**Comment by akolotov** [comment]
May we add an override for the STAKE token on xDai chain as so it does not require to approve/unlock the token transfer?

image

**Review by akolotov — APPROVED** [review]

**Pull request merged**
